on:
  pull_request:
  push:
    branches: [main, ui_tests]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Tests
        run: |
          pip install -e .[test]
          pytest -sv
